server:
  port: 8080

spring:
  application:
    name: game-review-service

  # Datasource config
  datasource:
    url: jdbc:h2:mem:gamereviewdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: none


#OpenAPI & Swagger Config
springdoc:
  api-docs:
    enabled: true
    path: /api-docs

# Log file config
logging:
  level:
    root: INFO
    org.hibernate: ERROR
  file:
    name: /var/game-review-service-log.log
